# Generated by Django 5.2.11 on 2026-02-28 04:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('site_type', models.CharField(choices=[('ECOM', 'E-commerce'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('primary_country_guess', models.CharField(blank=True, max_length=8, null=True)),
                ('country_confidence', models.FloatField(default=0.0)),
                ('overall_risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('trust_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=16)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('scan_version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='SeenSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('user_install_hash', models.CharField(max_length=128)),
                ('promoted_to_indexed', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['domain', 'first_seen_at'], name='guard_seens_domain_f7fc7e_idx')],
                'constraints': [models.UniqueConstraint(fields=('domain', 'user_install_hash'), name='uniq_seen_domain_install')],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('risk_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('triggered_by', models.CharField(choices=[('USER_VISIT', 'User Visit'), ('MANUAL_LOOKUP', 'Manual Lookup'), ('RECHECK', 'Recheck')], max_length=16)),
                ('raw_signals', models.JSONField(default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='guard.site')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_name', models.CharField(max_length=128)),
                ('risk_points', models.IntegerField()),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('HIGH', 'High')], max_length=16)),
                ('explanation', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='guard.scan')),
            ],
            options={
                'indexes': [models.Index(fields=['check_name'], name='guard_check_check_n_6c1a94_idx'), models.Index(fields=['severity'], name='guard_check_severit_b43e56_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_type', models.CharField(choices=[('HTML_HASH', 'HTML Hash'), ('SCREENSHOT', 'Screenshot'), ('POLICY_EXTRACT', 'Policy Extract')], max_length=32)),
                ('content_hash', models.CharField(max_length=255)),
                ('stored_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_snapshots', to='guard.site')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot_type'], name='guard_evide_snapsho_b4401f_idx')],
            },
        ),
    ]
