# Generated by Django 5.2.11 on 2026-02-28 06:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('install_hash', models.CharField(db_index=True, max_length=128)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('install_hash', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CONSUMED', 'Consumed'), ('EXPIRED', 'Expired'), ('DENIED', 'Denied')], default='PENDING', max_length=16)),
                ('interval_seconds', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_device_auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApiRefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('install_hash', models.CharField(db_index=True, max_length=128)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('access_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='guard.apiaccesstoken')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotated_from', to='guard.apirefreshtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_refresh_tokens', to=settings.AUTH_USER_MODEL)),
                ('created_from_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_refresh_tokens', to='guard.deviceauthsession')),
            ],
        ),
        migrations.AddField(
            model_name='apiaccesstoken',
            name='created_from_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_access_tokens', to='guard.deviceauthsession'),
        ),
        migrations.AddIndex(
            model_name='deviceauthsession',
            index=models.Index(fields=['status', 'expires_at'], name='guard_devic_status_f57cda_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceauthsession',
            index=models.Index(fields=['install_hash', 'created_at'], name='guard_devic_install_719630_idx'),
        ),
        migrations.AddIndex(
            model_name='apirefreshtoken',
            index=models.Index(fields=['user', 'install_hash'], name='guard_apire_user_id_a5c56e_idx'),
        ),
        migrations.AddIndex(
            model_name='apirefreshtoken',
            index=models.Index(fields=['expires_at', 'revoked_at'], name='guard_apire_expires_91bae2_idx'),
        ),
        migrations.AddIndex(
            model_name='apiaccesstoken',
            index=models.Index(fields=['user', 'install_hash'], name='guard_apiac_user_id_70334e_idx'),
        ),
        migrations.AddIndex(
            model_name='apiaccesstoken',
            index=models.Index(fields=['expires_at', 'revoked_at'], name='guard_apiac_expires_90164e_idx'),
        ),
    ]
