# Generated by Django 5.2.11 on 2026-02-28 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0002_apiaccesstoken_deviceauthsession_apirefreshtoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BrandDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('domain_type', models.CharField(choices=[('CANONICAL', 'Canonical'), ('REGIONAL', 'Regional Official'), ('PARTNER', 'Partner Official')], default='CANONICAL', max_length=16)),
                ('is_official', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='seed', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='guard.brand')),
            ],
            options={
                'ordering': ['domain'],
                'indexes': [models.Index(fields=['domain', 'is_active'], name='guard_brand_domain_34a823_idx'), models.Index(fields=['brand', 'is_active'], name='guard_brand_brand_i_b46f0f_idx')],
            },
        ),
    ]
